#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  mohamedchebbbi_frontend
        bind *:80
        mode http
        default_backend mohamedchebbbi_backend
backend mohamedchebbbi_backend
        balance roundrobin
        server 24812-web-01 54.208.28.27:80 check
        server 24812-web-02 54.157.170.238:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy config file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx
sudo service haproxy restart
